config/routes.rb
Rails.application.routes.draw do

  get 'charges/new'

  get 'charges/create'

  get 'njmjofficials/pres'
  get 'njmjofficials/secretary'
  get 'njmjofficials/treasurer'
  get 'njmjofficials/vp'
  get 'njmjofficials/parlimentarian'
  get 'njmjofficials/programming'
  get 'njmjofficials/recruit_retain_director'
  get 'njmjofficials/marketing_pr'
  get 'njmjofficials/community_serv_dir'
  get 'njmjofficials/historian'

  get 'welcome/about'
  get 'welcome/clicker'
  get 'welcome/grow'
  get 'welcome/ideas'
  get 'welcome/index'
  get 'welcome/invest'
  get 'welcome/interviews'
  get 'welcome/musicClasses'
  get 'welcome/networking'
  get 'welcome/njmj'
  get 'welcome/njmj_letsdothis'
  get 'welcome/loan'
  get 'welcome/pricing'
  get 'welcome/mailinglistdnp'
  get 'welcome/sisterSites'
  get 'welcome/stockwatch'
  get 'welcome/ticket_handeling'
  get 'welcome/topgolf'
  get 'welcome/topgolf_letsdothis'
  get 'welcome/value'
  get 'welcome/wine_budgeting'
  get 'welcome/WIPuns'
  get 'welcome/your_6_week_dev'

  get 'njmj/budderproductionnotes1'
  get 'njmj/bus_plan'
  get 'njmj/budderorder'
  get 'njmj/kellykustom'
  get 'njmj/notes'
  get 'njmj/media_drop'
  get 'njmj/meetingnotes'
  get 'njmj/membership'
  get 'njmj/meeting1'
  get 'njmj/secretary'
  get 'njmj/survey'

  get 'charges/new'
  get 'charges/budder_ord'
  get 'charges/charges'
  get 'charges/create'
  get 'charges/coffee'
  get 'charges/donate'
  get 'charges/food'
  get 'charges/gas'
  get 'charges/memberMonRec'
  get 'charges/memberWeekRec'
  get 'charges/memberYearRec'
  get 'charges/room'
  get 'charges/repair'

  get 'dwp/index'
  get 'dwp/set1'
  get 'dwp/cocaine1'
  get 'dwp/cocaine2'
  get 'dwp/cocaine3'
  get 'dwp/heroin1'
  get 'dwp/heroin2'
  get 'dwp/ketamine1'
  get 'dwp/lsd1'
  get 'dwp/lsd2'
  get 'dwp/mdma1'
  get 'dwp/mdma2'
  get 'dwp/meth1'
  get 'dwp/meth2'
  get 'dwp/misc1'
  get 'dwp/set1'
  get 'dwp/shrooms1'
  get 'dwp/shrooms2'
  get 'dwp/weed'
  get 'dwp/weed1'
  get 'dwp/weed2'
  get 'dwp/weed3'
  get 'dwp/weed4'
  resources :charges
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    @amount = params[:amount]

    @amount = @amount.gsub('$', '').gsub(',', '')

    begin
      @amount = Float(@amount).round(2)
    rescue
      flash[:error] = 'Charge not completed. Please enter a valid amount in USD ($).'
      redirect_to new_charge_path
      return
    end

    @amount = (@amount * 100).to_i # Must be an integer!

    if @amount < 200
      flash[:error] = 'Charge not completed. Donation amount must be at least $2.'
      redirect_to new_charge_path
      return
    end

    Stripe::Charge.create(
      :amount => @amount,
      :currency => 'usd',
      :source => params[:stripeToken],
      :description => 'Custom donation'
    )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
  end

app/controllers/dwp_controller.rb
class DwpController < ApplicationController
  def index
  end

  def set1
  end
end

app/controllers/njmj_controller.rb
class NjmjController < ApplicationController
  def notes
  end
end

app/controllers/njmjofficials_controller.rb
class NjmjofficialsController < ApplicationController
  def pres
  end

  def secretary
  end

  def treasurer
  end

  def vp
  end

  def parlimentarian
  end

  def programming
  end

  def recruit_retain_director
  end

  def marking_pr
  end

  def community_serv_dir
  end

  def historian
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def value
    

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/dwp_helper.rb
module DwpHelper
end

app/helpers/njmj_helper.rb
module NjmjHelper
end

app/helpers/njmjofficials_helper.rb
module NjmjofficialsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/budder_ord.html.erb
<p style="margin-bottom: 0in; line-height: 100%"><br/>
	<form action="https://getsimpleform.com/messages?form_api_token=b83fe0c887136349bbccf84ea8b5656c" method="post">

</p>
<p style="margin-bottom: 0in; line-height: 100%">Name</p>
<input type='text' name='name' /><br/>
<p style="margin-bottom: 0in; line-height: 100%">Address</p>
<input type='text' name='address' id='address' /><br/>
<p style="margin-bottom: 0in; line-height: 100%">Phone</p>
<input type='text' name='phone' id='phone' /><br/>
<p style="margin-bottom: 0in; line-height: 100%">Email</p>
<input type='text' name='email' /><br/>
<p style="margin-bottom: 0in; line-height: 100%">Date</p>
<input type='text' name='date' id='date'/><br/>
<p style="margin-bottom: 0in; line-height: 100%">Age</p>
<input type='text' name='date' id='age'/><br/>

<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>


</div>
<p style="margin-bottom: 0in; line-height: 100%">	Stick of
  Cannabutter ( ~110 grams, 375 mg THC OG Kush.)</p>
  <p style="margin-bottom: 0in; line-height: 100%">	Price : $10.00</p>

  <p style="margin-bottom: 0in; line-height: 100%">Quantity</p>
  <input type='text' name='quant' id='quant' value=2 /><br/>
  <p style="margin-bottom: 0in; line-height: 100%">Subtotal</p>
  <%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
    <% end %>
    <label class="amount">
      <span id="amtdesc">A Monthly Recurring membership for budder : $40</span>
    </label>
  </article>


  <p style="margin-bottom: 0in; line-height: 100%">Shipping method</p>
<div id="nextfriday">Today (is supposed to be the coming friday) </div>
<!-- <input type='text' name='shippingMeth' id='shippingMeth' /><br/> -->
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>




  <script>

  document.getElementById('nextfriday').innerHTML = "Personal delivery to you the Friday after " + new Date().toJSON().slice(0,10).replace(/-/g,'/');
  document.getElementById('date').value = new Date().toJSON().slice(0,10).replace(/-/g,'/');

  document.getElementById('amtdesc').innerHTML = document.getElementById('quant').value + " stick(s) of budder : $" + document.getElementById('quant').value*10;
  var description = document.getElementById('quant').value + " stick(s) of budder" ;
  function confirmalert(){
    alert("Your order has been submitted!");
  }
  function clicker(){
    return  document.getElementById('quant').value*1000;
  }
</script>
  <script

          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Stick(s) of Budder"
          data-amount="2000"
          data-locale="auto"
          >


  </script>
<% end %>




<input type='submit' value='Submit Order' onclick="confirmalert()"/>
</form>

app/views/charges/coffee.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Coffee and a snack. : $6.15</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Coffee and a snack."
          data-amount="615"
          data-locale="auto"></script>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you've helped to keep Anand going.<strong></strong>!</h2>
Click <%= link_to "Here", welcome_index_path %> to go back to TechIT,

app/views/charges/donate.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
      <article>
        <%= label_tag(:amount, 'Donation Amount:') %>
        <%= text_field_tag(:amount) %>
      </article>
      <article>
        <%= hidden_field_tag(:stripeToken) %>
      </article>
      <button id='donateButton'>Donate</button>
    <% end %>
<% end %>
<script>
$('#donateButton').on('click', function(e) {
  e.preventDefault();

  $('#error_explanation').html('');

  var amount = $('input#amount').val();
  amount = amount.replace(/\$/g, '').replace(/\,/g, '')

  amount = parseFloat(amount);

  if (isNaN(amount)) {
    $('#error_explanation').html('<p>Please enter a valid amount in USD ($).</p>');
  }
  else if (amount < 2.00) {
    $('#error_explanation').html('<p>Donation amount must be at least $2.</p>');
  }
  else {
    amount = amount * 100; // Needs to be an integer!
    handler.open({
      amount: Math.round(amount)
    })
    // Close Checkout on page navigation
    $(window).on('popstate', function() {
      handler.close();
    });
  }
});

</script>

app/views/charges/food.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Food for the day. : $14</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Food for the day."
          data-amount="1400"
          data-locale="auto"></script>
<% end %>

app/views/charges/gas.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>A tank of gas. : $23</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A tank of gas."
          data-amount="2300"
          data-locale="auto"></script>
<% end %>

app/views/charges/memberMonRec0.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>A Monthly Recurring membership for budder : $40</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Monthly Recurring Membership."
          data-amount="4000"
          data-locale="auto"></script>
<% end %>

app/views/charges/memberWeekRec.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>A Weekly Recurring membership for budder : $15</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Weekly Recurring Membership."
          data-amount="1500"
          data-locale="auto"></script>
<% end %>

app/views/dwp/set1.html.erb
<h1>Dwp#set1</h1>
<p>Find me in app/views/dwp/set1.html.erb</p>

app/views/njmj/meetingnotes.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<title></title>
	<meta name="generator" content="LibreOffice 5.1.6.2 (Linux)"/>
	<meta name="created" content="2018-02-02T17:55:03.474073496"/>
	<meta name="changed" content="2018-02-02T18:04:20.706097136"/>
	<style type="text/css">
		@page { margin: 0.79in }
		p { margin-bottom: 0.1in; line-height: 120% }
		a:link { so-language: zxx }
	</style>
</head>
<body lang="en-US" dir="ltr">
	<p style="margin-bottom: 0in; line-height: 100%"><br/>
		Available (fairly reliable) product suppliers: <br />

		<%= link_to "California", dwp_weed_path %>
		<br />
		<%= link_to "Massachusetts", dwp_weed3_path %>
		<br />
		<%= link_to "Mexico", dwp_weed1_path %>
		<br />
		<%= link_to "Germany", dwp_weed2_path %>
		<br />
		<%= link_to "Holland", dwp_weed4_path %> <br />
		(<%= link_to "Message me privately", welcome_mailinglistdnp_path %>
		if you find something interesting)
		<br />
		<%= link_to "Or Click Here if you'd like to receive updates when the pages update", welcome_mailinglistdnp_path %>
		<br />
		<br />
		<br />
		<br />
		<br />
	</p>
	<h2>Official meeting notes</h2>


<form action="https://getsimpleform.com/messages?form_api_token=b83fe0c887136349bbccf84ea8b5656c" method="post">
	<p style="margin-bottom: 0in; line-height: 100%">Submit a topic</p>
	<input type='text' name='topic' /><br/>
  <input type='submit' value='submit.' />
</form>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
</body>
</html>

app/views/njmj/secretary.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<title></title>
	<meta name="generator" content="LibreOffice 5.1.6.2 (Linux)"/>
	<meta name="created" content="2018-02-04T21:50:04.722343934"/>
	<meta name="changed" content="2018-02-04T22:01:29.951040056"/>
	<style type="text/css">
		@page { margin: 0.79in }
		p { margin-bottom: 0.1in; line-height: 120% }
		a:link { so-language: zxx }
	</style>
</head>
<body lang="en-US" dir="ltr">
	<form action="https://getsimpleform.com/messages?form_api_token=b83fe0c887136349bbccf84ea8b5656c" method="post">
		<%= link_to "See all notes", njmj_notes_path %> <br />


		<%= link_to "See previous meeting", njmj_meetingnotes_path %> <br />


<p style="margin-bottom: 0in; line-height: 100%"><a href="http://www.semo.edu/pdf/old/Lead_OfficerRoles_2009.pdf">Secretary
Duties</a></p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Date of the meeting:</p>
<input type='text' name='MeetingDate' /><br/>

<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Time the meeting was
called to order:</p>
<input type='text' name='meetingordertime' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Names of the meeting
participants and absentees:</p>
<input type='text' name='participantsandabsent' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Corrections and
amendments to previous meeting minutes:</p>
<input type='text' name='corrections' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Additions to the
current agenda:</p>
<input type='text' name='additions' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Whether a quorum is
present:</p>
<input type='text' name='quorum' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Motions taken or
rejected:</p>
<input type='text' name='motions' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Voting-that there
was a motion and second, and the outcome of the vote:</p>
<input type='text' name='voting' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Actions taken or
agreed to be taken:</p>
<input type='text' name='actionsto' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Next steps:</p>
<input type='text' name='steps' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Items to be held
over:</p>
<input type='text' name='heldover' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">New business:</p>
<input type='text' name='newbus' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Open discussion or
public participation:</p>
<input type='text' name='opendiscuss' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Next meeting date
and time:</p>
<input type='text' name='nextmeet' /><br/>
<p style="margin-bottom: 0in; line-height: 100%"><br/>


</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Time of adjournment:</p>
<input type='text' name='adjourn' /><br/>

<p style="margin-bottom: 0in; line-height: 100%">Posthumos Notes:</p>
<input type='text' name='Notes' /><br/>

<p style="margin-bottom: 0in; line-height: 100%"><br/>

	<input type='submit' value='submit.' />
</form>
</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
</body>
</html>

app/views/welcome/njmj_letsdothis.html.erb
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<title></title>
	<meta name="generator" content="LibreOffice 5.1.6.2 (Linux)"/>
	<meta name="created" content="00:00:00"/>
	<meta name="changed" content="2018-01-13T16:41:23.166162033"/>
	<meta name="created" content="00:00:00">
	<meta name="changed" content="2018-01-13T14:37:36.051786486">
	<meta name="created" content="2018-01-12T20:19:04.552831740">
	<meta name="changed" content="2018-01-12T21:53:55.747050964">
	<style type="text/css">
		@page { margin: 0.79in }
		p { margin-bottom: 0.1in; line-height: 120% }
		h3.western { font-family: "Liberation Sans", sans-serif }
		h3.cjk { font-family: "Noto Sans CJK SC Regular" }
		h3.ctl { font-family: "FreeSans" }
		a:link { so-language: zxx }
	</style>
</head>
<body lang="en-US" dir="ltr">
<%= link_to "Current agenda and secretary's notes.", njmj_notes_path %><br /> (updated feb 19)

<br />
<br />
<h3>Pages made on Feb 21 </h3>

<%= link_to "Kelly's Oil Order.", njmj_kellykustom_path %><br />
The following sites are to help streamline forms, duties, and a general gist for Officials. <br />
<%= link_to "President's Duties.", njmjofficials_pres_path %><br />
<%= link_to "VP Duties.", njmjofficials_vp_path %><br />
<%= link_to "Treasurer's Duties.", njmjofficials_treasurer_path %><br />
<%= link_to "Secretary's Duties.", njmjofficials_secretary_path %><br />
<%= link_to "Parlimentarian Duties.", njmjofficials_parlimentarian_path %><br />
<%= link_to "Programming Duties.", njmjofficials_programming_path %><br />
<%= link_to "Recruiting and Retention Director Duties.", njmjofficials_recruit_retain_director_path %><br />
<%= link_to "Marketing and PR Duties.", njmjofficials_marketing_pr_path %><br />
<%= link_to "Community Services Director Duties.", njmjofficials_community_serv_dir_path %><br />
<%= link_to "Historian's Duties.", njmjofficials_historian_path %><br />
<br />
<%= link_to "Weed Supplies catalog and order form.", njmj_meetingnotes_path %> with meeting notes at the end.<br />

<h3>Pages made on Feb 16 </h3>
<%= link_to "Membership page.", njmj_membership_path %><br />
<%= link_to "production 1 notes for budder.", njmj_budderproductionnotes1_path %><br />
<%= link_to "Survey for consumers and product reviews.", njmj_survey_path %><br />
<%= link_to "Budder Order page.", njmj_budderorder_path %><br />



<h3 class="western">Contributors:</h3>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">Vedabrat Anand
	Etwaru</p>
	<p style="margin-bottom: 0in; line-height: 100%">Kelly</p>
<p style="margin-bottom: 0in; line-height: 100%">Norma</p>
<p style="margin-bottom: 0in; line-height: 100%">Diana</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<h3 class="western">Proposed Funding
</h3>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0in; line-height: 100%">$14k - $24k</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<h3 class="western">Jobs Volunteered for:</h3>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<p>Programming</p>
<p>Pres</p>
<p>Secretary</p>
<p>Treasurer</p>
<p>VP</p>
<p>Historian</p>


<p style="margin-bottom: 0in; line-height: 100%">Comptroller</p>
<p style="margin-bottom: 0in; line-height: 100%">Operations</p>
<p style="margin-bottom: 0in; line-height: 100%">Supply Chain Manager</p>
<h3 class="western">Meeting Agenda Topics:</h3>
<p style="margin-bottom: 0in; line-height: 100%">General Positions</p>
<p style="margin-bottom: 0in; line-height: 100%">Implementation</p>
<p style="margin-bottom: 0in; line-height: 100%">Final Picture</p>
<p style="margin-bottom: 0in; line-height: 100%">Suppliers/Producers</p>
<p style="margin-bottom: 0in; line-height: 100%">Retail/Sales</p>
<p style="margin-bottom: 0in; line-height: 100%">Operations&amp;Management</p>
<p>Parlimentarian</p>
<p>Recruit_retain_director</p>
<p>Marketing_pr</p>
<p>community_serv_dir</p>
<p style="margin-bottom: 0in; line-height: 100%">Type of
business<br/>
Branding</p>
<p style="margin-bottom: 0in; line-height: 100%">Markets</p>
<p style="margin-bottom: 0in; line-height: 100%"><br/>

</p>
<h3 class="western">Valued Roles (needed):</h3>
<p style="margin-bottom: 0in; line-height: 100%">Treasurer, Secretary, President, Vice President, Land owner</p>
<p style="margin-bottom: 0in; line-height: 100%">Gardener</p>
<p style="margin-bottom: 0in; line-height: 100%">Engineer</p>
<p style="margin-bottom: 0in; line-height: 100%">Baker</p>
<p style="margin-bottom: 0in; line-height: 100%">Driver</p>
<p style="margin-bottom: 0in; line-height: 100%">Accountant</p>
<p style="margin-bottom: 0in; line-height: 100%">Marketing</p>
<p style="margin-bottom: 0in; line-height: 100%">Sales</p>
<p style="margin-bottom: 0in; line-height: 100%">Retail</p>
<p style="margin-bottom: 0in; line-height: 100%">Janitor</p>
<p style="margin-bottom: 0in; line-height: 100%">Payroll Assistant</p>
</br>
</br>
</br>
</br>

<p style="margin-bottom: 0in; line-height: 100%">different potencies for baked goods</p>
<p style="margin-bottom: 0in; line-height: 100%">place special custom orders for events</p>
<p style="margin-bottom: 0in; line-height: 100%">chocolate</p>
<p style="margin-bottom: 0in; line-height: 100%">lollipop(resale)</p>
<p style="margin-bottom: 0in; line-height: 100%">brownies</p>
<p style="margin-bottom: 0in; line-height: 100%">Gummy bears(rose gummy bears)</p>
<p style="margin-bottom: 0in; line-height: 100%">sour strings (we want, but we dont know how to make)</p>
<p style="margin-bottom: 0in; line-height: 100%">cookies</p>
<p style="margin-bottom: 0in; line-height: 100%">Muffins</p>
<p style="margin-bottom: 0in; line-height: 100%">cupcakes</p>
<p style="margin-bottom: 0in; line-height: 100%">membership (points and assortments)</p>
<p style="margin-bottom: 0in; line-height: 100%">contest (positively oriented)</p>
<p style="margin-bottom: 0in; line-height: 100%">lipstick taffy</p>
<p style="margin-bottom: 0in; line-height: 100%">Sexily named products</p>
<p style="margin-bottom: 0in; line-height: 100%">Spray bottle(for women)</p>
<p style="margin-bottom: 0in; line-height: 100%">Hard candy -s you hard</p>
<p style="margin-bottom: 0in; line-height: 100%"></p>
<p style="margin-bottom: 0in; line-height: 100%"></p>
<p style="margin-bottom: 0in; line-height: 100%"></p>
<p style="margin-bottom: 0in; line-height: 100%"></p>
<p style="margin-bottom: 0in; line-height: 100%"></p>


</body>
</html>

app/views/welcome/value.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>



I value ____________ (make a method that takes this input and adds it to an array/database)





 top 30 things in the database below | clicks | likes | upvotes | downvotes